### ISSUE TITLE
Add an option to not use heterogeneous=True for task groups in experiment

### ISSUE THREAD

**Issue by Kipok** [NVIDIA/NeMo-Run#17]
In our workflow we frequently need to run multiple srun commands in parallel, but on the same set of nodes (e.g. to host a server and a client that doesn't actually need GPUs, but they require different containers). Currently I can pass multiple scripts to the experiment.add method, but whenever I do that it treats them as het jobs and separates on multiple nodes. Can we add an option to instead do a simpler

```
srun cmd1 &
srun cmd2 &
...
srun cmdN &
wait
```
with a single slurm header instead? This will require some changes in the materialize code as well and I'm not sure how common this pattern is, but I don't think there is another way to support this workflow with experiment api otherwise. Please let me know if I'm missing something and there is indeed a way to do that

**Comment by hemildesai** [comment]
Done in https://github.com/NVIDIA/NeMo-Run/commit/73d5e1998e525e6addc4a095cf71d4f4c914f4f3
