### ISSUE TITLE
Add support for local execution with docker container and task groups

### ISSUE THREAD

**Issue by Kipok** [NVIDIA/NeMo-Run#26]
We need the support in local scheduler to provide docker container, mounts as well as number of gpus and tasks. We also need it to support task groups, which should accept their own containers/mounts for each task, so that we can launch the same workflows as running on slurm (e.g. server-client). All tasks in a group would start in parallel and run until any of them fail or finish normally

**Comment by hemildesai** [comment]
NeMo-Run now supports Docker executor.
