### ISSUE TITLE
Have an option to throw an error if there are uncommitted changes when packaging the code

### ISSUE THREAD

**Issue by Kipok** [NVIDIA/NeMo-Run#40]
It would be good to have an option in GitPackager to stop with error if there are uncommitted changes. As far as I understand, they are ignored at the moment (so only the last committed version is actually used) and this can lead to silent errors in experiments that might be very costly (users expect the latest code to be there but get a previously committed version instead).

**Comment by hemildesai** [comment]
Sounds good, we will implement this option soon.
