### ISSUE TITLE
Can't pass in dtype via CLI

### ISSUE THREAD

**Issue by sweiss-google** [NVIDIA/NeMo-Run#98]
Hi, I'm trying to pass in the pipeline_dtype on the command line:

```
nemo llm pretrain --factory=llama3_8b trainer.devices=2 trainer.strategy.pipeline_model_parallel_size=2 trainer.strategy.pipeline_dtype=torch.bfloat16
```

It doesn't work with any of the following: `b16`, `bf16`, `bfloat16`, `torch.bfloat16`

How do I pass this in?

**Comment by hemildesai** [comment]
@marcromeyn Can you take a look at this? Thanks

**Comment by marcromeyn** [comment]
Thanks for reporting this! I put in a small fix: https://github.com/NVIDIA/NeMo-Run/pull/99
